make cert job depend on patch job create/complete + update secret if exists

diff --git a/charts/all/amd-llm-init/templates/init-istio-ca-secret-cm.yaml b/charts/all/amd-llm-init/templates/init-istio-ca-secret-cm.yaml
--- a/charts/all/amd-llm-init/templates/init-istio-ca-secret-cm.yaml
+++ b/charts/all/amd-llm-init/templates/init-istio-ca-secret-cm.yaml
@@ -11,21 +11,21 @@ data:
     echo "Starting secret sync script"
 
     UPSTREAM_EXISTS=$(oc get secret --ignore-not-found -n istio-system knative-serving-cert)
-    EXISTS=$(oc get secret --ignore-not-found rhoai-ca-bundle)
+    EXISTS=$(oc get secret --ignore-not-found -n {{ .Values.global.amdllm.namespace }} rhoai-ca-bundle)
 
     if [[ -z "${UPSTREAM_EXISTS}" ]]; then
-      echo "upstream found"
-    else
-      echo "upstream not found"
+      echo "upstream secret in istio-system required for copy, but not found"
+      exit 1
     fi
 
     if [[ -z "${EXISTS}" ]]; then
       echo "creating secret..."
       oc create secret generic -n {{ .Values.global.amdllm.namespace }} rhoai-ca-bundle --from-literal=tls.crt="$(oc extract secret/knative-serving-cert -n istio-system --to=- --keys=tls.crt)"
-      echo "done creating secret."
-      exit
+      echo "done."
     else
-      echo "oc get secret --ignore-not-found rhoai-ca-bundle returned non-empty string, not creating a secret"
+      echo "updating secret..."
+      oc create secret generic -n {{ .Values.global.amdllm.namespace }} rhoai-ca-bundle --dry-run=client -o yaml --from-literal=tls.crt="$(oc extract secret/knative-serving-cert -n istio-system --to=- --keys=tls.crt)" | oc replace -f -
+      echo "done."
     fi
 
-    echo "script bottom"
+    exit 0
